services:
  - type: web
    name: track-tech-website
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
